### PR TITLE
Add swap file

### PR DESCRIPTION
**Pull request by kfriedman**
Heyo!

We're trying to add the creation of a swap file as part of our standard Beanstalk config. 

For more context, see:
https://github.com/NYPL/dgx-new-arrivals/pull/4

### CODE REVIEW

**Comment by nodanaonlyzuul** [comment]
I'd be interested in how we can document common `.ebextensions` configs.
We always want cloudwatch and swap space. Maybe we should start by putting a template of .ebextensions in `engineering-general`, `aws`, or some other repo?

Or build a [yeoman-](http://yeoman.io/)like generator in the long run.

**Comment by kfriedman** [comment]
That's a great idea @nodanaonlyzuul! 

Also, having the common `eb create` commands there would be awesome.

**Comment by nodanaonlyzuul** [comment]
kewl. Where's the best place for it to live?
general-engineering for now?

**Comment by kfriedman** [comment]
I think `engineering-general` is right. Maybe we should create a deployment section?

**Comment by rhernand3z** [comment]
I agree, we should centralize documentation... I figured the AWS repository would be the right place... given the name...

I also want to note that it is important to document the application's README because that is the FIRST place developers will visit to get started.

@EdwinGuzman, @kfriedman and I have been working hard to update the README to include:

1) GIT Workflow
2) AWS Configuration/Deployment
3) CI/CD Workflow

SEE: https://github.com/NYPL/dgx-new-arrivals

**Comment by nodanaonlyzuul** [comment]
Yeah! 

I agree that a README is the best place for some documentation and Greg K has done awesome work in https://github.com/NYPL/engineering-general/blob/master/standards/documentation.md.

@kfriedman: 

I could see us having a:

./deployment/elastic-beanstalk
./deployment/lambda
./deplayment/ecs....

Right?

**Pull request merged**
