### PR TITLE
Pb/filters

### PR DESCRIPTION
**Pull request by nonword**
This PR adds:
 - filters
 - rewritten README and swagger documentation

This is extensive, but should be backwards compat. Happy to walk people through it and discuss front-end integration.

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
Looks good from first glance. From the doc and the image below: should "series" and "call number" be removed from the search box filter search?

screen shot 2017-05-15 at 4 37 17 pm

I'm going to try it locally, but if it's backwards compatible, there shouldn't be an issue merging.

**Comment by EdwinGuzman** [comment]
When I try these filters
* `http://local.nypl.org:3003/api/v0.1/discovery/resources?filters[dateCreated]=1999`
* `http://local.nypl.org:3003/api/v0.1/discovery/resources?filters[language]=lang:eng`

I get the following error:

> error: "[query_parsing_exception] query_string must be provided with a [query], with { index=resources-2017-05-08 line=1 col=212 }"

This one returns results `http://local.nypl.org:3003/api/v0.1/discovery/resources?q=hamilton&filters[dateCreated]=1999&per_page=4` but it doesn't seem like `dateCreated` of 1999 was picked up.

**Comment by nonword** [comment]
Please pull latest. Documentation was about the createdYear filter and I neglected to make the `q` param optional per docs.

**Comment by nonword** [comment]
> Looks good from first glance. From the doc and the image below: should "series" and "call number" be removed from the search box filter search?

My understanding is the search box drop-down controls a special `search_scope` param, which governs what properties the `q` param matches against. It's different from this new `filters` param, which can be used in tandem to `search_scope` & `q` pairs. The `filters` param should typically be used solely in conjunction with aggregations ("facets") to match specific property values (i.e. no partial/ fuzzy matching when using `filters`, so it really shouldn't be entered by a user).

**Comment by EdwinGuzman** [comment]
That makes sense. Thanks, all the examples work now.

I need to better understand making ES queries but that shouldn't block this PR.

**Comment by ablwr** [comment]
I trust you both.

**Pull request merged**
